version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    command: postgres -c 'max_connections=200'
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.17.1
    command: [ "--log-level=debug" ]
    ports:
      - "1000:16686"

  otlp-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otlp-collector-config.yaml", "--log-level=debug" ]
    depends_on:
      - jaeger
    volumes:
      - ./otlp-collector-config.yaml:/etc/otlp-collector-config.yaml
    ports:
      - "9000:9000"