version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    command: postgres -c 'max_connections=200'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter
